name: salutation sur un jour quelconque

on: workflow_dispatch

env:
 DAY: $DAY_OF_WEEK ## Variable d'environnement pour l'ensemble du flux de travail
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
     Popp: $Greeting
    steps:
      - name: "Dites Salut Push nous sommes lundi"
        run: echo "$Greeting $First_Name. Nous sommes $DAY_OF_WEEK!"
        env:
          First: $First_Name
