name: salutation sur un jour quelconque

on: workflow_dispatch

env:
 DAY:  ${{ vars.DAY_OF_WEEK }} ## Variable d'environnement pour l'ensemble du flux de travail
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
     Popp:  ${{ vars.Greeting }}
    steps:
      - name: "Dites Salut Push nous sommes lundi"
        run: echo "$Popp $First. Nous sommes $DAY!"
        env:
          First: ${{ vars.First_Name }}
